### ISSUE TITLE
Keyfile located  in the initramfs not being decrypted

### ISSUE THREAD

**Issue by ghost** [xdbob/mkinitcpio-gpg-encrypt#1]
Hi,

I installed your AUR package and I seem to have some issues. I followed all your instructions, but once I try to boot I get the following message:

```
No key available with this passphrase.
Invalid keyfile. Reverting to passphrase.
```

Furthermore, I don't get prompted for my pin for my YubiKey Neo. To test this further I added the GPG encrypted keyfile to my LUKS. This immediately worked, but of course should not happen. It seems my GPG encrypted file it immediately given to the decryption process of the LUKS volume.

My keyfile is located in the root directory and is called `crypto_keyfile.bin.gpg`, I added this to my mkinitcpio.conf

`FILES="/crypto_keyfile.bin.gpg"`

and this is my GRUB Kernel command line (without UUID):

`GRUB_CMDLINE_LINUX="cryptdevice=UUID=XXXXX cryptkey=rootfs:/crypto_keyfile.bin.gpg"`

Any idea what might be wrong or how I could debug this further? Thank you for any help you might be able to offer!

**Comment by xdbob** [comment]
Hi,

It looks like the module is not loaded.
The keyfile name is *.gpg the first printed line should be 

> GPG file detected, trying to decrypt

Did you replace "encrypt" by "gpg-encrypt" in your mkinitcpio.conf ? and if so have you regenerated your initramfs (`mkinitcpio -p linux`) ?

My commandline looks like this : `cryptdevice=UUID=XXX:luksLvm cryptkey=UUID=XXX:vfat:keyfile.gpg root=/dev/mapper/main-root rw`

Ho and thanks for the feedback.

**Comment by xdbob** [comment]
My bad, the module did not flag the GPG keyfile if it was bundled in the initramfs (`cryptkey=rootfs:XXX.gpg`).

I am currently testing a fix.

**Comment by xdbob** [comment]
It should be fixed.

**Comment by ghost** [comment]
Hey,

yes that did it. Thanks for the fix!
